import os
import json
from groq import Groq

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

def analyze_with_llm(text):
    """
    Signal 1: LLM-based classification via Groq API.
    Returns a dict with 'score' (float 0-1) and 'reasoning' (str).
    """
    if not GROQ_API_KEY:
        raise ValueError("GROQ_API_KEY not found in environment")
    
    client = Groq(api_key=GROQ_API_KEY)
    
    prompt = f"""Analyze the following text and determine whether it was written by a human or generated by AI.

Evaluate on these 4 dimensions (0-100 each):
1. Voice authenticity: Does the text have a distinctive, personal voice?
2. Transition naturalness: Do ideas flow organically or feel templated?
3. Contextual specificity: Are there concrete details tied to lived experience?
4. Structural predictability: Is the structure formulaic or surprising?

Text to analyze:
\"\"\"{text}\"\"\"

Respond ONLY with valid JSON in this exact format:
{{"dimension_scores": {{"voice": int, "transitions": int, "specificity": int, "predictability": int}}, "average_score": int, "assessment": "human"|"ai"|"uncertain", "brief_reasoning": str}}

Where average_score is the mean of the 4 dimensions. Higher scores = more human-like."""
    
    try:
        chat_completion = client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.1-8b-instant",
            temperature=0.1,
            max_tokens=500
        )
        
        response_text = chat_completion.choices[0].message.content.strip()
        
        # Extract JSON from response (handle potential markdown fences)
        if "```json" in response_text:
            json_str = response_text.split("```json")[1].split("```")[0].strip()
        elif "```" in response_text:
            json_str = response_text.split("```")[1].split("```")[0].strip()
        else:
            json_str = response_text
        
        result = json.loads(json_str)
        
        # Convert average_score (0-100) to normalized score (0-1)
        avg_score = result.get("average_score", 50)
        normalized_score = avg_score / 100.0
        
        return {
            "score": normalized_score,
            "reasoning": result.get("brief_reasoning", "No reasoning provided"),
            "assessment": result.get("assessment", "uncertain"),
            "dimension_scores": result.get("dimension_scores", {})
        }
        
    except Exception as e:
        # Fallback: return uncertain score if API fails
        return {
            "score": 0.5,
            "reasoning": f"API error or parsing failure: {str(e)}",
            "assessment": "uncertain",
            "dimension_scores": {}
        }